Add a `.gitignore.dist` file
alleyinteractive/byline-manager pull request #71
Opened 2022-04-27 21:54 UTC by ostowe

This commit will include built files for this plugin in VIP deploys in cases where the plugin is included via submodule.

2022-04-28 15:47 UTC, benpbolton requested changes
I think I'd remove (or update) the incorrect comment line at a minimum... totes up to you whether you'd like to add new exclusions to the .gitignore and new .gitignore.dist ... and I wonder if we should start this file with a comment describing what a .gitignore.dist is?

2022-04-28 15:47 UTC, benpbolton commented on .gitignore.dist
> +# Client build files
Only sanity-test item difference between this and the `built` branch .gitignore is that the build branch also excludes `.npm`, which seems like a fine thing to ignore in both the .gitignore and .gitignore.dist files... might be worth adding.

2022-04-28 15:47 UTC, benpbolton commented on .gitignore.dist
> +# Client build files
I might recommend removing or renaming `Client build files`, as it is no longer excluding 'Client build files' .. in fact, the comment is quite contrary to what it is doing...  /vendor could, for all intents, be listed right alongside node_modules/ or the others if needed...

2022-04-29 18:21 UTC, closed without merging

2022-04-29 18:21 UTC, ostowe commented
Closing this b/c there's a `built` branch, which I was unaware of when I created it!